spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csye6225?createDatabaseIfNotExist=true
    username: root
    password: ${CSYE6225_PSQL_DB_PWD}
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    converters:
      preferred-json-mapper: gson
server:
  port: 8080