spring:
  datasource:
    url: ${CSYE6225_MSQL_DB_CONNSTR}
    username: ${CSYE6225_MSQL_DB_USER}
    password: ${CSYE6225_MSQL_DB_PWD}
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    converters:
      preferred-json-mapper: gson
server:
  port: 8080