name: Java Maven CI Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Google cloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.CSYE6225_MSQL_DB_NAME }};" -u${{ secrets.CSYE6225_MSQL_DB_USER }} -p${{ secrets.CSYE6225_MSQL_DB_PWD }}

      - name: Write spring config from secrets
        uses: DamianReeves/write-file-action@master
        with:
          path: 'src/main/resources/application.yml'
          write-mode: overwrite
          contents: |
            spring:
              datasource:
                url: ${{ secrets.CSYE6225_MSQL_DB_CONNSTR }}
                username: ${{ secrets.CSYE6225_MSQL_DB_USER }}
                password: ${{ secrets.CSYE6225_MSQL_DB_PWD }}
                driverClassName: com.mysql.cj.jdbc.Driver
              mvc:
                converters:
                  preferred-json-mapper: gson
              cloud:
                  gcp:
                    project-id: ${CSYE6225_PROJECT_ID}
            server:
              port: ${{ secrets.CSYE6225_SERVER_PORT }}

      - name: Build application with Maven
        run: mvn clean install

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init ./webapp.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: |
          if ! packer validate ./webapp.pkr.hcl ; then
            echo "Validation check failed"
            exit 1
          fi

      - name: Run `packer fmt`
        id: fmt
        run: |
          if ! packer fmt -check ./webapp.pkr.hcl ; then
            echo "Formatting check failed"
            exit 1
          fi
