name: Build packer image after merge

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CSYE6225_MSQL_DB_PWD }}
          MYSQL_DATABASE: ${{ secrets.CSYE6225_MSQL_DB_NAME }}
          MYSQL_USER: test
          MYSQL_PASSWORD: ${{ secrets.CSYE6225_MSQL_DB_PWD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Google cloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Write spring config from secrets
        uses: DamianReeves/write-file-action@master
        with:
          path: 'src/main/resources/application.yml'
          write-mode: overwrite
          contents: |
            spring:
              datasource:
                url: ${{ secrets.CSYE6225_MSQL_DB_CONNSTR }}
                username: ${{ secrets.CSYE6225_MSQL_DB_USER }}
                password: ${{ secrets.CSYE6225_MSQL_DB_PWD }}
                driverClassName: com.mysql.cj.jdbc.Driver
              mvc:
                converters:
                  preferred-json-mapper: gson
            server:
              port: ${{ secrets.CSYE6225_SERVER_PORT }}
              cloud:
                gcp:
                  project-id: ${CSYE6225_PROJECT_ID}

      - name: Build application with Maven
        run: mvn clean install

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init ./webapp.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: echo "SOURCE_IMAGE=$(packer build -machine-readable . | grep -m 1 "A disk image was created" | awk '{print $NF}')" >> $GITHUB_ENV

      - name: Get
        id: get_source_name_zone
        run: |
          read -r name zone <<< $(gcloud compute instance-groups managed list-instances ${{ secrets.MIG_NAME }} --region=${{ secrets.REGION }} | awk '/HEALTHY/{print $1, $2; exit}')
          echo "SOURCE_INSTANCE_NAME=$name" >> $GITHUB_ENV
          echo "ZONE=$zone" >> $GITHUB_ENV

      - name: Recreate instance template
        id: recreate_template
        run: |
          echo "TEMPLATE_NAME=$(gcloud compute instance-templates create "${{ secrets.INSTANCE_TEMPLATE_PREFIX }}-$(date +%s)" \
          --source-instance=${{ env.SOURCE_INSTANCE_NAME }} \
          --source-instance-zone=${{ env.ZONE }} \
          --instance-template-region=${{ secrets.REGION }} \
          --image=${{ env.SOURCE_IMAGE }} \
          --configure-disk=device-name=${{ secrets.DISK_DEVICE_NAME }},auto-delete=true | awk 'NR==2{print $1}')" >> $GITHUB_ENV

      - name: Update Managed Instance Group with New Template
        id: update_mig
        run: |
          gcloud compute instance-groups managed set-instance-template ${{ secrets.MIG_NAME }} \
          --template=projects/${{ secrets.CSYE6225_PROJECT_ID }}/regions/${{ secrets.REGION }}/instanceTemplates/${{ env.TEMPLATE_NAME }} \
          --region=${{ secrets.REGION }}

      - name: Rolling start update
        id: group_update
        run: |
          gcloud compute instance-groups managed rolling-action start-update ${{ secrets.MIG_NAME }} \
          --version=template=projects/${{ secrets.CSYE6225_PROJECT_ID }}/regions/${{ secrets.REGION }}/instanceTemplates/${{ env.TEMPLATE_NAME }} \
          --region=${{ secrets.REGION }}

      - name: Update status check
        id: update_status
        run: gcloud compute instance-groups managed wait-until ${{ secrets.MIG_NAME }} --version-target-reached --region=${{ secrets.REGION }}
