name: Run Tests Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CSYE6225_MSQL_DB_PWD }}
          MYSQL_DATABASE: ${{ secrets.CSYE6225_MSQL_DB_NAME }}
          MYSQL_USER: test
          MYSQL_PASSWORD: ${{ secrets.CSYE6225_MSQL_DB_PWD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write spring config from secrets
        uses: DamianReeves/write-file-action@master
        with:
          path: 'src/main/resources/application.yml'
          write-mode: overwrite
          contents: |
            spring:
              datasource:
                url: ${{ secrets.CSYE6225_MSQL_DB_CONNSTR }}
                username: ${{ secrets.CSYE6225_MSQL_DB_USER }}
                password: ${{ secrets.CSYE6225_MSQL_DB_PWD }}
                driverClassName: com.mysql.cj.jdbc.Driver
              mvc:
                converters:
                  preferred-json-mapper: gson
            server:
              port: ${{ secrets.CSYE6225_SERVER_PORT }}

      - name: Build application with Maven
        run: mvn clean install
